#!/usr/bin/env python3
"""Build the curation intake form for adding new terms to the prioritised list.

    docs/forms/rd-list-curation-form.xlsx

The form asks for the minimum a human must supply, and nothing else. What
decides that minimum is `config/prioritisation_criteria.yaml`: an entry earns
its place on the site by satisfying criteria, and only four fields feed signals
that no recipe can derive. Everything else is either resolved from Mondo at
ingest (label, synonyms, xrefs, the six categories), generated by a build
(`value_sets`, drug associations), or has no producer at all and stays blank
(the HPO fields, frozen since the Excel ingest was retired).

`justification_summary` is the load-bearing field — alone it gates three of the
six criteria — and the criteria config matches its values as exact literals, so
a typo silently fails a criterion with no error anywhere. That is why it is five
Y/N columns here rather than one free-text cell: a curator cannot misspell a
checkbox.

Run as `python scripts/build_curation_form.py` from anywhere.
"""
import sys
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.datavalidation import DataValidation

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "forms" / "rd-list-curation-form.xlsx"

FONT = "Arial"
REQUIRED_FILL = PatternFill("solid", fgColor="FFE699")   # amber: required on every row
ONEOF_FILL = PatternFill("solid", fgColor="FFF2CC")      # pale amber: at least one of the group
OPTIONAL_FILL = PatternFill("solid", fgColor="EDEDED")   # grey: optional
HEADER_FONT = Font(name=FONT, bold=True, size=10)
BODY_FONT = Font(name=FONT, size=10)
EXAMPLE_FONT = Font(name=FONT, size=10, italic=True, color="808080")
THIN = Side(style="thin", color="BFBFBF")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

# The five permissible justification_summary values, verbatim as the criteria
# config matches them. Changing a string here silently breaks a criterion.
JUSTIFICATIONS = [
    ("just_diagnostic_delay", "Diagnostic delay impact"),
    ("just_underdiagnosis", "Insufficient ICD coding/underdiagnosis"),
    ("just_intervention", "Intervention potential"),
    ("just_multimodal", "Multi-modal detectability"),
    ("just_phenotypic_complexity", "Phenotypic complexity"),
]

PREVALENCE = ["L", "H", "H_star", "H_uncertain"]

KEYWORDS = [
    "Adult", "Auditory", "Blood", "Bone", "Cardiac", "Congenital", "Connective",
    "Developmental", "Endocrine", "Exposure", "GI", "Genetic", "Hereditary",
    "Immune", "Infectious", "Metabolic", "Musculoskeletal", "Neoplastic",
    "Nephro", "Neuro", "Ophthalmic", "Pediatric", "Progressive", "Pulmonary",
    "Reproductive", "Skin", "Syndromic",
]

# (header, width, required, help text shown under the header)
COLUMNS = [
    ("mondo_id", 18, True,
     "MONDO:NNNNNNN. Everything else about the disease is looked up from this."),
    ("disease_name_check", 34, False,
     "Optional. The name as you know it. Checked against Mondo at ingest and "
     "warned on mismatch; never stored. A guard against pasting the wrong id."),
] + [
    (col, 14, "one_of", f'Set to Y if this applies. Writes the literal "{val}" '
                        f'into justification_summary.')
    for col, val in JUSTIFICATIONS
] + [
    ("prevalence_category", 20, True,
     "L, H, H_star or H_uncertain. H or H_star is half of the low-diagnostic-rate criterion."),
    ("keywords", 30, False,
     "Semicolon-separated, from the Lists sheet. Progressive and Syndromic are "
     "the direct route to the progressive/multisystem criterion."),
    ("misdiagnosis_bias", 34, False,
     "Free text. Who gets missed, and why. The other half of the "
     "low-diagnostic-rate criterion when prevalence is L."),
    ("additional_justification", 34, False,
     "Free text. Anything the five checkboxes above cannot say."),
]

EXAMPLE = ["MONDO:0018068", "trisomy 13", "Y", "Y", "", "", "Y", "L",
           "Congenital; Pediatric; Syndromic",
           "Frequently recorded only as the presenting malformation",
           "Patau syndrome; survival beyond infancy is rare but rising"]


def build():
    wb = Workbook()

    # ---------------------------------------------------------------- form --
    ws = wb.active
    ws.title = "New diseases"

    ws["A1"] = "Curation form — new entries for the prioritised rare disease list"
    ws["A1"].font = Font(name=FONT, bold=True, size=13)
    ws["A2"] = ("One row per disease. Amber = required on every row. Pale amber = the five "
                "reasons a disease belongs on the list; set at least one to Y. Grey = optional, "
                "safe to leave blank. Row 4 is an example and is skipped at ingest, so start "
                "typing at row 5. Hover any header for what it means; the Instructions sheet "
                "lists what gets filled in for you.")
    ws["A2"].font = Font(name=FONT, size=10, italic=True, color="595959")
    ws["A2"].alignment = Alignment(wrap_text=True, vertical="top")
    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=len(COLUMNS))
    ws.row_dimensions[2].height = 30

    for i, (name, width, required, help_text) in enumerate(COLUMNS, start=1):
        letter = get_column_letter(i)
        ws.column_dimensions[letter].width = width

        head = ws.cell(row=3, column=i, value=name)
        head.font = HEADER_FONT
        head.fill = {True: REQUIRED_FILL, "one_of": ONEOF_FILL}.get(required, OPTIONAL_FILL)
        head.border = BORDER
        head.alignment = Alignment(wrap_text=True, vertical="center")
        head.comment = None
        # The help text lives in a cell comment rather than a second header row,
        # so the header row stays machine-readable for the ingest script.
        from openpyxl.comments import Comment
        head.comment = Comment(help_text, "rd-list curation form", height=120, width=320)

        ex = ws.cell(row=4, column=i, value=EXAMPLE[i - 1])
        ex.font = EXAMPLE_FONT
        ex.border = BORDER

    ws.freeze_panes = "A4"
    ws.row_dimensions[3].height = 28

    # -------------------------------------------------------- validations --
    yn = DataValidation(type="list", formula1='"Y,N"', allow_blank=True,
                        showErrorMessage=True)
    yn.error = "Enter Y or N, or leave blank for N."
    yn.errorTitle = "Y or N"
    ws.add_data_validation(yn)
    for i, _ in enumerate(JUSTIFICATIONS, start=3):
        yn.add(f"{get_column_letter(i)}5:{get_column_letter(i)}500")

    prev_col = get_column_letter(3 + len(JUSTIFICATIONS))
    prevalence = DataValidation(
        type="list", formula1=f"=Lists!$B$2:$B${1 + len(PREVALENCE)}",
        allow_blank=False, showErrorMessage=True)
    prevalence.error = "Pick one of L, H, H_star, H_uncertain."
    prevalence.errorTitle = "Prevalence category"
    ws.add_data_validation(prevalence)
    prevalence.add(f"{prev_col}5:{prev_col}500")

    mondo = DataValidation(type="custom",
                           formula1=f'=OR(ISBLANK(A5),AND(LEFT(A5,6)="MONDO:",LEN(A5)=13))',
                           showErrorMessage=True)
    mondo.error = "A Mondo id looks like MONDO:0018068 — the prefix plus seven digits."
    mondo.errorTitle = "Check the Mondo id"
    ws.add_data_validation(mondo)
    mondo.add("A5:A500")

    # ------------------------------------------------------- instructions --
    ins = wb.create_sheet("Instructions")
    ins.column_dimensions["A"].width = 34
    ins.column_dimensions["B"].width = 96

    rows = [
        ("HOW TO USE THIS FORM", ""),
        ("", "One row per disease you want added. Fill the yellow columns; leave anything "
             "you do not know blank. Row 4 of the form is an example and is skipped at ingest."),
        ("", "Send the file back as-is. Do not add, rename or reorder columns — the ingest "
             "script reads the header row by name."),
        ("", ""),
        ("WHAT YOU MUST PROVIDE", ""),
        ("mondo_id", "The Mondo id. Every ontology-derived field is looked up from it, so "
                     "getting it right matters more than anything else on the row."),
        ("at least one just_* column = Y", "Why this disease belongs on the list. These five are "
                     "the whole controlled vocabulary; a row with none set is rejected, because "
                     "three of the six prioritisation criteria read this field and an entry "
                     "without it renders as a near-empty card on the site."),
        ("prevalence_category", "L, H, H_star (high in some populations) or H_uncertain."),
        ("", ""),
        ("WHAT IS FILLED IN FOR YOU — DO NOT SUPPLY", ""),
        ("mondo_label, mondo_synonyms", "Resolved from Mondo at ingest."),
        ("ontology_terminology_codes", "Mondo xrefs — OMIM, UMLS, MedGen, NORD, ICD-10-CM."),
        ("the six mondo_category_* fields", "just update-categories, over tmp/mondo.obo."),
        ("value_sets (ICD-10-CM codes)", "just build-value-sets, derived from Mondo. Curating "
                     "ICD codes is a separate job and is deliberately not part of this form."),
        ("indications, contraindications, research", "just build-drugs, from MeDIC."),
        ("", ""),
        ("WHAT STAYS BLANK, AND WHY", ""),
        ("hpo_high_level_categories", "No producer. These four came from the Excel spreadsheet "
                     "via an extractor retired in 87a76dd, and nothing re-derives them. Every "
                     "entry curated before April 2026 has them; new entries will not, until "
                     "someone writes a producer. See issues/issue_ontology_enrichment_dropped.md."),
        ("curated_hpo_profiles", "Same."),
        ("histopheno_categories", "Same."),
        ("hpo_treatment_rank", "Same."),
        ("work_capacity, care_dependence", "Curated in a separate lane by the curate-frailty "
                     "skill. Only 900 of 3,079 entries have them; not expected here."),
        ("", ""),
        ("DOES A BLANK HURT?", ""),
        ("", "Less than you would think. The frozen HPO fields only ever supply alternative "
             "routes to a criterion: phenotypic complexity also fires from the just_* columns, "
             "progressive/multisystem from keywords or the Mondo category, and accessible test "
             "from the genetic category or an OMIM xref. With the required columns plus keywords, "
             "all six criteria remain reachable."),
    ]
    for r, (a, b) in enumerate(rows, start=1):
        ca, cb = ins.cell(row=r, column=1, value=a), ins.cell(row=r, column=2, value=b)
        heading = a.isupper() and a != ""
        ca.font = Font(name=FONT, bold=True, size=11 if heading else 10)
        cb.font = BODY_FONT
        cb.alignment = Alignment(wrap_text=True, vertical="top")
        if b and len(b) > 110:
            ins.row_dimensions[r].height = 15 * (len(b) // 110 + 1)

    # -------------------------------------------------------------- lists --
    lists = wb.create_sheet("Lists")
    lists["A1"], lists["B1"], lists["C1"] = "justification (Y/N columns)", "prevalence_category", "keywords"
    for c in ("A1", "B1", "C1"):
        lists[c].font = HEADER_FONT
    for i, (_, val) in enumerate(JUSTIFICATIONS, start=2):
        lists.cell(row=i, column=1, value=val).font = BODY_FONT
    for i, val in enumerate(PREVALENCE, start=2):
        lists.cell(row=i, column=2, value=val).font = BODY_FONT
    for i, val in enumerate(KEYWORDS, start=2):
        lists.cell(row=i, column=3, value=val).font = BODY_FONT
    lists.column_dimensions["A"].width = 38
    lists.column_dimensions["B"].width = 22
    lists.column_dimensions["C"].width = 20
    lists.sheet_state = "hidden"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    wb.save(OUT)
    print(f"wrote {OUT}")
    print(f"  {len(COLUMNS)} columns: "
          f"{sum(1 for c in COLUMNS if c[2] is True)} required, "
          f"{len(JUSTIFICATIONS)} justification checkboxes (at least one), "
          f"{sum(1 for c in COLUMNS if c[2] is False)} optional")


if __name__ == "__main__":
    build()
