"""Merge the source disease list with drug, value-set, functional-capacity and DisMech data.

Four joins by MONDO ID, all into the curated list and none back out of it:
`data/drugs.yml` from MeDIC, `data/value_sets.yml` from Mondo,
`data/functional_capacity.yml` from Orphanet/SSA/state lists/HPOA, and
`tmp/mondo_emc.tsv` from the DisMech release.

The DisMech join is the one that reads a TSV rather than a generated YAML, and
deliberately has no `build_dismech.py` behind it: there is nothing to derive,
only one column to look up by MONDO ID, and an intermediate YAML would be a
verbatim re-encoding of the release asset.

The value-set join is tier-aware. `exact` and `narrower` are regenerated by
`build_value_sets.py` and always come from the derived file; `proxy` and
`excluded` are curated in the source and always survive. That asymmetry is the
whole point of the split, so it is enforced here rather than left to convention.
"""

import csv
from pathlib import Path

import click
import yaml


def load_yaml(path: Path) -> dict:
    """Load a YAML file, returning empty dict if missing or empty."""
    if not path.exists():
        return {}
    with open(path) as f:
        data = yaml.safe_load(f)
    return data if data else {}


def load_dismech(path: Path) -> dict[str, str]:
    """Read `mondo_id -> dismech_url` out of the DisMech release TSV.

    Rows without both columns filled are skipped rather than emitting an empty
    link; a disease DisMech does not cover simply gets no slot.
    """
    if not path.exists():
        return {}
    urls: dict[str, str] = {}
    with open(path, newline="") as f:
        for row in csv.DictReader(f, delimiter="\t"):
            mondo_id = (row.get("mondo_id") or "").strip()
            url = (row.get("dismech_url") or "").strip()
            if mondo_id and url:
                urls[mondo_id] = url
    return urls


# Slot order inside one value set, so the output reads strongest tier first.
VALUE_SET_ORDER = ["terminology", "exact", "narrower", "proxy", "excluded",
                   "mondo_version", "terminology_version", "generated_on"]

DERIVED_TIERS = ("exact", "narrower")
CURATED_TIERS = ("proxy", "excluded")


def merge_value_sets(curated: list[dict], derived: list[dict]) -> list[dict]:
    """Combine one disease's curated and derived value sets, by terminology."""
    by_terminology: dict[str, dict] = {}
    for vs in derived or []:
        by_terminology[vs["terminology"]] = dict(vs)
    for vs in curated or []:
        target = by_terminology.setdefault(vs["terminology"], {"terminology": vs["terminology"]})
        for tier in CURATED_TIERS:
            if vs.get(tier):
                target[tier] = vs[tier]
        # A curated value set for a terminology with no derived codes still needs
        # its stamps, but never overwrites the ones the build just wrote.
        for stamp in ("mondo_version", "terminology_version"):
            if vs.get(stamp) and not target.get(stamp):
                target[stamp] = vs[stamp]
    out = []
    for terminology in sorted(by_terminology):
        vs = by_terminology[terminology]
        if not any(vs.get(tier) for tier in DERIVED_TIERS + CURATED_TIERS):
            # Nothing survived: a curated block that only carried derived tiers,
            # which `build_value_sets.py` refuses and this drops rather than
            # emitting an empty value set.
            continue
        out.append({k: vs[k] for k in VALUE_SET_ORDER if vs.get(k)})
    return out


ASSESSMENTS = ("work_capacity", "care_dependence")

# Lanes that are functions of a source file, regenerated by
# build_functional_capacity.py. A copy of one of these in SOURCE is stale at best
# and hand-edited at worst, so the join drops it rather than trusting it.
DERIVED_LANES = frozenset({
    "EXPERT_DATABASE", "FEDERAL_POLICY_LIST", "STATE_POLICY_LIST",
    "PHENOTYPE_ANCHOR", "COMPUTED_SCORE",
})

# Strongest and most independent first, the model's own reading last.
LANE_ORDER = ["EXPERT_DATABASE", "LITERATURE", "FEDERAL_POLICY_LIST",
              "STATE_POLICY_LIST", "PHENOTYPE_ANCHOR", "COMPUTED_SCORE",
              "MODEL_JUDGEMENT"]


def merge_evidence(curated: list[dict], derived: list[dict]) -> list[dict]:
    """Re-attach the derived evidence lines to one assessment.

    Same asymmetry as the value sets: derived lanes always come from the
    generated file, curated lanes always survive from the source. A derived line
    edited by hand in SOURCE would simply be dropped here - which is the point.
    """
    kept = [e for e in (curated or []) if e.get("lane") not in DERIVED_LANES]
    combined = list(derived or []) + kept
    return sorted(combined, key=lambda e: LANE_ORDER.index(e["lane"])
                  if e.get("lane") in LANE_ORDER else len(LANE_ORDER))


def attach_dismech(disease: dict, url: str | None) -> None:
    """Set (or clear) one disease's `dismech_url`, in place.

    Derived like the value-set and evidence lanes above, so a copy found in the
    curated source is dropped rather than trusted. Re-inserted next to the labels
    it belongs with instead of appended after the evidence, because the merged
    list is committed and read by people as well as by the site.
    """
    had = disease.pop("dismech_url", None) is not None
    if not url:
        return
    if not had and ("mondo_label" in disease or "mondo_synonyms" in disease):
        items = list(disease.items())
        after = "mondo_synonyms" if "mondo_synonyms" in disease else "mondo_label"
        at = [k for k, _ in items].index(after) + 1
        rebuilt = items[:at] + [("dismech_url", url)] + items[at:]
        disease.clear()
        disease.update(rebuilt)
    else:
        disease["dismech_url"] = url


def merge(source_path: Path, drugs_path: Path, value_sets_path: Path | None = None,
          functional_capacity_path: Path | None = None,
          dismech_path: Path | None = None) -> dict:
    """Merge drug, value-set, functional-capacity and DisMech data into the source list.

    Returns a new dict with indications/research/contraindications,
    `value_sets` and `dismech_url` merged per disease by MONDO ID.
    """
    source = load_yaml(source_path)
    drugs = load_yaml(drugs_path)
    value_sets = load_yaml(value_sets_path) if value_sets_path else {}
    fc = load_yaml(functional_capacity_path) if functional_capacity_path else {}
    dismech = load_dismech(dismech_path) if dismech_path else {}

    # Index drug data by disease ID
    drug_map: dict[str, dict] = {}
    for entry in drugs.get("diseases", []):
        disease_id = entry.get("disease_id")
        if disease_id:
            drug_map[disease_id] = entry

    value_set_map: dict[str, list[dict]] = {
        entry["mondo_id"]: entry.get("value_sets", [])
        for entry in value_sets.get("diseases", [])
        if entry.get("mondo_id")
    }

    fc_map: dict[str, dict] = {
        entry["mondo_id"]: entry
        for entry in fc.get("diseases", [])
        if entry.get("mondo_id")
    }

    # Merge into source diseases
    merged_count = 0
    value_set_count = 0
    fc_count = 0
    dismech_count = 0
    for disease in source.get("diseases", []):
        mondo_id = disease.get("mondo_id")
        if not mondo_id:
            continue
        if mondo_id in drug_map:
            drug_entry = drug_map[mondo_id]
            for field in ("indications", "contraindications", "research"):
                if field in drug_entry:
                    disease[field] = drug_entry[field]
            merged_count += 1

        fc_entry = fc_map.get(mondo_id)
        if fc_entry:
            for slot in ASSESSMENTS:
                a = disease.get(slot)
                if isinstance(a, dict):
                    a["evidence"] = merge_evidence(a.get("evidence"), fc_entry.get(slot))
            fc_count += 1

        curated = disease.get("value_sets") or []
        derived = value_set_map.get(mondo_id, [])
        if curated or derived:
            disease["value_sets"] = merge_value_sets(curated, derived)
            value_set_count += 1

        if dismech:
            url = dismech.get(mondo_id)
            attach_dismech(disease, url)
            if url:
                dismech_count += 1

    click.echo(f"Merged drug data for {merged_count} diseases")
    if value_sets:
        click.echo(f"Merged value sets for {value_set_count} diseases")
    if fc:
        click.echo(f"Merged functional-capacity evidence for {fc_count} diseases")
    if dismech:
        click.echo(f"Merged DisMech links for {dismech_count} diseases")
    return source


@click.command()
@click.option(
    "--source",
    "-s",
    "source_path",
    required=True,
    type=click.Path(exists=True, path_type=Path),
    help="Path to the source disease list YAML (without drugs).",
)
@click.option(
    "--drugs",
    "-d",
    "drugs_path",
    required=True,
    type=click.Path(exists=True, path_type=Path),
    help="Path to the drugs association YAML.",
)
@click.option(
    "--functional-capacity",
    "-f",
    "functional_capacity_path",
    required=False,
    default=None,
    type=click.Path(exists=True, path_type=Path),
    help="Path to the derived functional-capacity evidence YAML.",
)
@click.option(
    "--dismech",
    "-m",
    "dismech_path",
    required=False,
    default=None,
    type=click.Path(path_type=Path),
    help="Path to the DisMech release TSV (tmp/mondo_emc.tsv) for the linkout join.",
)
@click.option(
    "--value-sets",
    "-v",
    "value_sets_path",
    type=click.Path(path_type=Path),
    default=None,
    help="Path to the derived value-set YAML from build_value_sets.py.",
)
@click.option(
    "--output",
    "-o",
    "output_path",
    required=True,
    type=click.Path(path_type=Path),
    help="Path to write the merged output YAML.",
)
def main(source_path: Path, drugs_path: Path, output_path: Path,
         value_sets_path: Path | None, functional_capacity_path: Path | None,
         dismech_path: Path | None):
    """Merge the source disease list with drug, value-set, functional-capacity and DisMech data."""
    data = merge(source_path, drugs_path, value_sets_path, functional_capacity_path,
                 dismech_path)

    with open(output_path, "w") as f:
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False)

    click.echo(f"Wrote {len(data.get('diseases', []))} diseases to {output_path}")


if __name__ == "__main__":
    main()
